<a href="https://colab.research.google.com/github/ankawm/Udemy-Data-Science/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: anka.w.m@gmail.com


### NumPy
>Biblioteka: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja biblioteki: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>NumPy to biblioteka programistyczna dla języka Python, dodająca obsługę dużych, wielowymiarowych tabel i macierzy. NumPy to otwarte oprogramowanie i posiada wielu autorów. [Wikipedia](https://pl.wikipedia.org/wiki/NumPy)  
>
>Instalować bibliotekę NumPy w notebookach, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)

### <a name='a1'></a> Podstawy

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x = np.array([1.3, 2.1, 5.6])
print(x)

[1.3 2.1 5.6]


In [12]:
x.dtype

dtype('float64')

2D Array

In [13]:
x = np.array([[1, 3], [-3, 3]])

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 2)

In [18]:
x = np.array([[1, 2, 7], [-1, 3, 4]])
print(x)

[[ 1  2  7]
 [-1  3  4]]


In [19]:
x.shape

(2, 3)

3D Array

In [20]:
x = np.array([[[1, 2, 7], 
               [-1, 3, 4]],
              
              [[6, 1, 27], 
               [-2, 2, 7]]
              ])

### <a name='a2'></a> Typy danych

In [23]:
A =  np.array([1, 2, 7])
A.dtype

dtype('int64')

In [25]:
B =  np.array([1.0, 5.2, 3.7])
B.dtype

dtype('float64')

In [28]:
C =  np.array([1, 3, 7], dtype='float')
C.dtype

dtype('float64')

In [29]:
D =  np.array([2, 5, 3], dtype='complex')
D.dtype

dtype('complex128')

In [30]:
E =  np.array([1.0, 5.2, 3.7], dtype='int')
E.dtype

dtype('int64')

In [31]:
print(E)

[1 5 3]


In [32]:
F =  np.array([True, False])
F.dtype

dtype('bool')

In [33]:
G =  np.array([24, 120, 230], dtype=np.int8)
G.dtype

dtype('int8')

In [34]:
H =  np.array([24, 120, 230], dtype=np.uint8)
H.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [35]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones(shape=(3, 3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
np.full(shape=(5, 5), fill_value=4,dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(start=5, stop=10)
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [40]:
np.arange(start=5, stop=10, step=2)
np.arange(5, 10, 2)

array([5, 7, 9])

In [43]:
np.arange(start=5, stop=10, step=0.2)
np.arange(5, 10, 0.2)

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4,
       7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [45]:
#generowanie okreslonej liczebności danych 
np.linspace(start=0, stop=1, num=11)
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [46]:
A = np.arange(15)
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [49]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [50]:
A + B

array([6, 0, 7, 4])

In [58]:
np.add(A, B)

array([6, 0, 7, 4])

In [51]:
A - B

array([0, 2, 1, 0])

In [59]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [52]:
A * B

array([ 9, -1, 12,  4])

In [60]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [53]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [61]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [54]:
A + 3

array([6, 4, 7, 5])

In [55]:
A - 3

array([ 0, -2,  1, -1])

In [56]:
A * 3

array([ 9,  3, 12,  6])

In [57]:
A + 3*B

array([12, -2, 13,  8])

In [65]:
#Mnożenie macierzy
X = np.array([[2, 4], 
              [6, 8],
              [1, 9]])
Y = np.array([[3, -4, 6], 
              [2, -5, 9]])

print(X)
print(Y)

[[2 4]
 [6 8]
 [1 9]]
[[ 3 -4  6]
 [ 2 -5  9]]


In [ ]:
# X * Y tu będzie błąd złe wymiary tablic

In [67]:
np.dot(X, Y)

array([[ 14, -28,  48],
       [ 34, -64, 108],
       [ 21, -49,  87]])

In [68]:
X.dot(Y)

array([[ 14, -28,  48],
       [ 34, -64, 108],
       [ 21, -49,  87]])

In [69]:
Y.dot(X)

array([[-12,  34],
       [-17,  49]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [71]:
np.random.seed(10)

In [72]:
np.random.randn()

1.331586504129518

In [73]:
np.random.randn(10)

array([ 0.71527897, -1.54540029, -0.00838385,  0.62133597, -0.72008556,
        0.26551159,  0.10854853,  0.00429143, -0.17460021,  0.43302619])

In [74]:
np.random.randn(10, 4)

array([[ 1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  ],
       [-1.07980489, -1.97772828, -1.7433723 ,  0.26607016],
       [ 2.38496733,  1.12369125,  1.67262221,  0.09914922],
       [ 1.39799638, -0.27124799,  0.61320418, -0.26731719],
       [-0.54930901,  0.1327083 , -0.47614201,  1.30847308],
       [ 0.19501328,  0.40020999, -0.33763234,  1.25647226],
       [-0.7319695 ,  0.66023155, -0.35087189, -0.93943336],
       [-0.48933722, -0.80459114, -0.21269764, -0.33914025],
       [ 0.31216994,  0.56515267, -0.14742026, -0.02590534]])

In [75]:
np.random.rand()

0.8261228438427398

In [76]:
np.random.rand(10)

array([0.25137413, 0.59737165, 0.90283176, 0.53455795, 0.59020136,
       0.03928177, 0.35718176, 0.07961309, 0.30545992, 0.33071931])

In [77]:
np.random.rand(10, 3)

array([[0.7738303 , 0.03995921, 0.42949218],
       [0.31492687, 0.63649114, 0.34634715],
       [0.04309736, 0.87991517, 0.76324059],
       [0.87809664, 0.41750914, 0.60557756],
       [0.51346663, 0.59783665, 0.26221566],
       [0.30087131, 0.02539978, 0.30306256],
       [0.24207588, 0.55757819, 0.56550702],
       [0.47513225, 0.29279798, 0.06425106],
       [0.97881915, 0.33970784, 0.49504863],
       [0.97708073, 0.44077382, 0.31827281]])

In [80]:
np.random.randint(10)

5

In [81]:
np.random.randint(low=10, high=101)

83

In [83]:
np.random.randint(10, 100)

50

In [84]:
np.random.choice([4, 2, 5, 9])

2

In [85]:
np.random.choice(['python', 'java', 'sql', 'C'])

'C'

In [87]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.random.shuffle(data)
data

array([2, 6, 9, 1, 3, 4, 0, 5, 8, 7])

### <a name='a6'></a> Podstawowe funkcje

In [89]:
np.exp(1)

2.718281828459045

In [91]:
np.sqrt(9)

3.0

In [96]:
np.all([3, 1, 8])

True

In [94]:
np.any([0, 0, 0])

False

In [99]:
bool(4.6)

True

In [103]:
A = np.random.rand(5)
A

array([0.00291609, 0.29544213, 0.98688912, 0.23833271, 0.73339648])

In [104]:
np.argmax(A)

2

In [105]:
A[np.argmax(A)]

0.9868891220137718

In [106]:
np.argmin(A)

0

In [108]:
A[np.argmin(A)]

0.0029160883463633658

In [109]:
np.argsort(A)

array([0, 3, 1, 4, 2])

In [110]:
np.max(A)

0.9868891220137718

In [112]:
np.min(A)

0.0029160883463633658

In [113]:
np.mean(A)

0.4513953069925606

In [114]:
np.median(A)

0.2954421349382369

In [115]:
np.std(A)

0.35696749274085376

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [117]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
A[2]

2

In [119]:
A[3:5]

array([3, 4])

In [120]:
A[:5]

array([0, 1, 2, 3, 4])

In [122]:
A[16:]

array([16, 17, 18, 19])

In [124]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [125]:
A[0]

array([0, 1, 2, 3, 4])

In [127]:
A[:, -2]

array([ 3,  8, 13, 18])

In [128]:
A[1, 1]

6

In [129]:
A[1, 3]

8

In [131]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [132]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [133]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [136]:
[print(row) for row in A]

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


[None, None, None, None]

In [134]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [135]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [137]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [138]:
A.shape

(4, 5)

In [139]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [140]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [141]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [148]:
A = np.arange(-10, 10, 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [149]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [150]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [151]:
A[np.bitwise_and(A >- 5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [152]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])